# Requirements

- context provided by ECMWF meeting
- framework adhering to rOpenSci practices
- tools are limited to standard code devops
- funding would cover food drinks, space, and a small prize for best visuals, general purpose function?

## People

As the hack-a-ton would benefit from the context of ECMWF backgrounds the proposed workshop would be co-located with a broader conference / workshop with respect to ECMWF data use and product development. Assuring participants not only to R based processing but also the potential of scaling smaller projects or proof of concepts if deemed necessary.

## Processes

By default development will happen in an open way through using a github repository hosted by ? (rOpenSci), ensuring a proper hand-over to a larger developing community after more rigorous review. During development and the hack-a-ton workshop rOpenSci development standards will be followed. This includes the codes of conduct, coding style and licensing.

## Tools & Tech

The proposed workshop will rely on standard code development tools such as github and Travis CI continous integration. Few additional technological requirements are needed.

## Funding

We ask for $10 000 in funding to cover this hack-a-ton (rough guestimate, should check budget previous small meetings).

## Summary

..

