# Success

Success will be defined by the development of a first skeleton `ecmwfrExtra` package with at least 5 well documented domain specific functions, and 5 two general purpose functions.

We acknowledge that these numbers are ad-hoc. However, the main incentive for the workshop would be to make sure that contributions to ECMWF R based package development are not one sides, focussing on a few scientific domains. A diversity of contributions from different fields, reflected in different discipline bound functions would be the most prominent indicator of success.

## Definition of done

The package will remain open for development after the workshop. The purpose is therefore less to attain a permanent status of "done" rather to spur on development. In this sense, if development continues after the hack-a-ton we would consider the job "done".

## Measuring success

...

## Future work

...

## Key risks

Risks involve the process of motivating people for the hack-a-ton, and gaps in knowledge skill in using certain tools (mainly git) when trying to contribute to the project.

Although pre-requisits can be listed when putting out the call for participants we would like to include as many participants as possible. However, we will make sure to advertise that a certain level of proficiency in R and git is required. In this sense we will not strictly teach code development, only guide people where necessary and bring people into one space to learn from one another.